set -g default-terminal "tmux-256color"
set -g status-left-length 30
set -g status-right-length 30
set -g focus-events on
set -g allow-passthrough on
set -g mouse on

set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

set-window-option -g mode-keys vi
set-option -g history-limit 10000
